@isTest
public class ApplicantPortal_Controller_Test {
	
	@isTest
    public static void testCoverage(){
        ApplicantPortal_Contoller.firstTestMethod1();
        ApplicantPortal_Contoller.firstTestMethod2();
	    ApplicantPortal_Contoller.firstTestMethod3();
        ApplicantPortal_Contoller.firstTestMethod4();
	    ApplicantPortal_Contoller.firstTestMethod5();
        ApplicantPortal_Contoller.firstTestMethod6();
	    ApplicantPortal_Contoller.firstTestMethod7();
        ApplicantPortal_Contoller.firstTestMethod33();
    }
}