@isTest
public class IndustrialFellowshipHelper_Test2 {
	
   /* @isTest
    public static void testCoverage(){
        IndustrialFellowshipHelper.firstTestMethod1();
        IndustrialFellowshipHelper.firstTestMethod2();
	    IndustrialFellowshipHelper.firstTestMethod3();
        IndustrialFellowshipHelper.firstTestMethod4();
        IndustrialFellowshipHelper.firstTestMethod5();
        IndustrialFellowshipHelper.firstTestMethod6();
        IndustrialFellowshipHelper.firstTestMethod7();
        IndustrialFellowshipHelper.firstTestMethod8();
    }*/
    
    
}