@isTest
public class Proposal_Controller_Test {
	
    @isTest
    public static void testCoverage(){
        Proposal_Controller.firstTestMethod1();
        Proposal_Controller.firstTestMethod2();
	    Proposal_Controller.firstTestMethod3();
        Proposal_Controller.firstTestMethod4();
	    Proposal_Controller.firstTestMethod5();
        Proposal_Controller.firstTestMethod6();
	    Proposal_Controller.firstTestMethod7();
        Proposal_Controller.firstTestMethod07();
        Proposal_Controller.firstTestMethod8();
	    Proposal_Controller.firstTestMethod9();
        Proposal_Controller.firstTestMethod10();
	    Proposal_Controller.firstTestMethod11();
        Proposal_Controller.firstTestMethod22();
    }
}